### PR TITLE
Switched to Demands >= 4.0.0

### PR DESCRIPTION
**Pull request by ekoval**
Part of: https://github.com/yola/production/issues/3484

### CODE REVIEW

**Comment by snitch** [comment]
:sparkles: No lint errors found. :sparkles:

**Comment by stefanor** [comment]
Err what was the needless code that was removed? I'm just seeing a demands upgrade.

**Comment by stefanor** [comment]
And we have some test failures under python 3.2, that are a bit confusing :) Time to update the python3 verions we test with?

**Comment by ekoval** [comment]
i actually test it using python 2.7

**Comment by stefanor** [comment]
Travis tests it under Python 3 too.

**Comment by ekoval** [comment]
So, it that correct that only tests under Py3.2 didn't pass. 3.3, 3.4 - ok?

**Comment by snitch** [comment]
:sparkles: No lint errors found. :sparkles:

**Comment by RayeN** [comment]
:+1: The changes look good, but PR name is confusing :)

**Comment by stefanor** [comment]
Oh I was assuming we'd add 3.5 too. I mean, why not?

**Pull request merged**
