### PR TITLE
Fix RST rendering on Pypi

### PR DESCRIPTION
**Pull request by adrianmoisey**
srsly.

### CODE REVIEW

**Comment by snitch** [comment]
:sparkles: No lint errors found. :sparkles:

**Comment by stefanor** [comment]
How does this help?

I'd have thought the problem is that we aren't telling it to do anything with the README

**Comment by adrianmoisey** [comment]
> How does this help?

Without this change: http://pypi.python.org/pypi/pycloudflare
With this change: https://testpypi.python.org/pypi/pycloudflare

**Comment by jouberthenk** [comment]
:+1:

**Comment by stefanor** [comment]
Ah, I didn't know it fished out `README.rst` itself. It used to use the `long_description` from `setup.py` (so many `setup.py`s read `README.rst`)

:+1:

**Pull request merged**
