### PR TITLE
Support Page Rule APIs

### PR DESCRIPTION
**Pull request by stefanor**
They have been available (in BETA) for a year:

* https://blog.cloudflare.com/today-is-a-big-day-for-page-rules-2/
* https://api.cloudflare.com/#page-rules-for-a-zone-properties

### CODE REVIEW

**Comment by snitch** [comment]
:sparkles: No lint errors found. :sparkles:

**Comment by stefanor** [comment]
:bell: @yola/service-engineering

**Comment by jamesodo** [comment]
Needs a changelog entry. Everything else looks good.

**Comment by snitch** [comment]
:sparkles: No lint errors found. :sparkles:

**Pull request merged**
